# Generated by Django 3.2.5 on 2022-01-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_medicine_time2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='time2',
        ),
        migrations.AddField(
            model_name='medicine',
            name='mail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
