# Generated by Django 3.2.5 on 2022-01-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220110_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='leaflet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
