# Generated by Django 3.2.5 on 2022-01-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_medicine_leaflet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine_Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa Produktu Leczniczego')),
                ('name2', models.CharField(max_length=255, verbose_name='Nazwa powszechnie stosowana')),
                ('power', models.CharField(max_length=255, verbose_name='Moc')),
                ('form', models.CharField(max_length=255, verbose_name='Substancja czynna')),
                ('active_substance', models.CharField(max_length=255, verbose_name='Ulotka')),
                ('characteristics', models.CharField(max_length=255, verbose_name='Charakterystyka')),
            ],
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='create',
        ),
    ]
