# Generated by Django 3.2.5 on 2022-01-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220118_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='dose',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jednorazowa dawka'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='how_much',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wielkość opakowania'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='package',
            field=models.IntegerField(blank=True, null=True, verbose_name='Liczba posiadanych opakowań'),
        ),
    ]
