# Generated by Django 3.2.5 on 2022-01-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20220118_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_database',
            name='active_substance',
            field=models.CharField(max_length=255, verbose_name='Substancja czynna'),
        ),
        migrations.AlterField(
            model_name='medicine_database',
            name='form',
            field=models.CharField(max_length=255, verbose_name='Postać farmaceutyczna'),
        ),
    ]
