# Generated by Django 3.2.5 on 2022-01-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20220118_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='doses',
            field=models.IntegerField(blank=True, null=True, verbose_name='Liczba dostępnych dawek'),
        ),
    ]
