# Generated by Django 3.2.5 on 2022-02-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_medicine_doses'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='notification1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Powiadomienie1'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='notification2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Powiadomienie2'),
        ),
    ]
